import uuid
import datetime
import json


class InvalidAmountError(Exception):
    pass

class InsufficientFundsError(Exception):
    pass


# Step 2 from the README. 
# The empty structure that will hold transactions.
transactions = []

def build_transaction(action, amount):
    transactions_fields = {
    "id": uuid.uuid4(),
    "amount": amount,
    "action": action,
    "date": datetime.datetime.now()
}
    return transactions_fields

def load_ledger(filename="ledger.json"):
    try:
        with open(filename, "r") as f:
            loaded_data = json.load(f)
    except FileNotFoundError:
        print(f"The requested file could not be found!:{filename}")
    except json.JSONDecodeError:
        print("No existing ledger found, starting fresh")
    else:
        print("File loaded successfully.")               
        transactions.clear()
        transactions.extend(loaded_data)


def prepare_for_save(transactions):
    jsonified_transactions = [
        {"id": str(transaction["id"]), 
         "amount":transaction["amount"],
           "action":transaction["action"], 
           "date":str(transaction["date"])}
             for transaction in transactions]
    return jsonified_transactions


def save_ledger(filename="ledger.json"):
    jsonified_transactions = prepare_for_save(transactions) 
    with open(filename, "w") as f:
        json.dump(jsonified_transactions,f)

# Step 3
# Function that allows deposits(add_deposit)
# Algorithm. 
   # def the add_deposit function. Its parameter will be  amount.  ID, type, and date will be generated by the function
   # Append deposit to transactions as a dictionary containing the amount, ID, type, and date.


def add_deposit(amount):
    if (amount <= 0):
        raise InvalidAmountError(f"You can't deposit zero or a negative amount: {amount}")   
    transactions.append(build_transaction("deposit", amount))


def check_balance():
    available_balance = 0

    for transaction in transactions:
        if transaction["action"] == 'deposit':
            available_balance += transaction["amount"]
        elif transaction["action"] == 'withdrawal':
            available_balance -= transaction["amount"]

    return available_balance

# Step 4 
# Function that checks the available balance
# Loops through the ledger(transactions) and computes net balance
# Algorithm
    # define a function 'check_balance'. It doesn't take in any parameter.
    # initialize a variable available_balance that stores the initial account's net balance. Initialize it to 0 since no transaction has happened at this stage. We have an empty ledger
    # Loops through the list to check transaction type
    # If type is deposit, add deposit amount to available_balance
    # If type is withdrawal, substract withdrawal amount from available_balance
    # return the net balance
    # call check_balance




def add_withdrawal(amount):
    current_balance = check_balance()
    if (amount <= 0):
        raise InvalidAmountError(f"You can't withdraw Ksh 0 or less: {amount}")
    
    if (amount > current_balance ):
        raise InsufficientFundsError(f"You have insufficients funds to withdraw: {amount}")
    
    transactions.append(build_transaction("withdrawal", amount))


#step 8. A function that lists and filters transactions depending on action type
"""def list_transactions(action=???):
    loop through transactions
    for each one, decide: should it be printed?
        - if action is ??? (nothing was passed), print everything
        - otherwise, only print if the transaction's action matches"""

def list_transactions(action=None):
    for transaction in transactions:
        if (action == None) or  transaction["action"] == action:
            print (f"You made a {transaction["action"]} in the amount of {transaction["amount"]}")
                
  

      
        
        